### ISSUE TITLE
Locations are not serialized if they only stored a single field

### ISSUE THREAD

**Issue by bendoerr** [angusmcleod/discourse-locations#3]
When I create a topic with both the this and an event from your events plugin. Only the event gets saved and the location is dropped. Logs indicate that the location was posted, but the resulting topic only has the event. I'll try to debug further. Let me know what other information I can provide.

```
Processing by PostsController#create as JSON
  Parameters: {"raw"=>"This is a topic that has a location on it and a date.", "title"=>"Testing Topic with Mapzen Location", "unlist_topic"=>"false", "category"=>"4", "is_warning"=>"false", "archetype"=>"regular", "typing_duration_msecs"=>"8400", "composer_open_duration_msecs"=>"60795", "featured_link"=>"", "event"=>{"start"=>"2017-10-11T11:30:00-04:00", "end"=>"2017-10-11T12:30:00-04:00"}, "location"=>{"geo_location"=>{"lat"=>"38.031128", "lon"=>"-78.477673", "address"=>"Court Square Tavern, 500 Court Sq, Charlottesville, Virginia, 22902, United States", "city"=>"Charlottesville", "state"=>"Virginia", "postalcode"=>"22902", "countrycode"=>"United States"}}, "nested_post"=>"true"}
Completed 200 OK in 551ms (Views: 3.3ms | ActiveRecord: 237.7ms)
```

**Comment by angusmcleod** [comment]
I have seen this issue before, but I can never repro it. Is there anything else at all in the logs during posting or when loading the topic view? Have you got access to the db? Check if the table ``topic_custom_fields`` has a location for that topic.

<img width="636" alt="screenshot at oct 02 07-57-18" src="https://user-images.githubusercontent.com/5931623/31060477-6abc7fe0-a747-11e7-894c-fa8081a5d297.png">

I made a topic with your exact params on my sandbox and it worked normally.

https://discourse.angusmcleod.com.au/t/testing-topic-with-mapzen-location/66

**Comment by bendoerr** [comment]
Yep, looks like it's in the database. So it the issue is probably on the display side? I'm able to reproduce whenever I don't set a custom name.

To narrow it down a bit further I've confirmed that the location is not returned in the pre-store value for the topic though, so the issue doesn't seem to be in the ember code. I'll try to dig more later today.

**Comment by bendoerr** [comment]
Forgot to say, I can reproduce with just setting a location alone. So events probably are not related.

**Comment by bendoerr** [comment]
Reproduced in your sandbox https://discourse.angusmcleod.com.au/t/topic-w-location-wo-name/68

**Comment by angusmcleod** [comment]
Fixed in https://github.com/angusmcleod/discourse-locations/pull/5
