### ISSUE TITLE
Default location field is shown in the user-card

### ISSUE THREAD

**Issue by sudaraka94** [angusmcleod/discourse-locations#31]
Default location field is shown in the user-card and it's not editable anymore. Suggestions were made to add the map-location instead of the traditional location field in the user-card.

**Comment by angusmcleod** [comment]
@sudaraka94 Yup, looks good. Any further discussion specific to this issue we can have here.

**Comment by sudaraka94** [comment]
@angusmcleod I love the idea of managing things on github. :smile:
