### ISSUE TITLE
Add warning in the Map location field to warn users about the privacy implications

### ISSUE THREAD

**Issue by yanokwa** [angusmcleod/discourse-locations#33]
We should warn users about the privacy implications of setting a map location. I would propose placing some text below the Map Location text field that says:

> :warning:️ Your map location will be shown to all users! Choose your level of privacy by setting map location to your town, your province, or even your country.

This text would be styled just like the text after Profile Background. That is, light grey and small.

**Comment by yanokwa** [comment]
An alternate approach would include helper text inside the text box. I do not like that approach as much because it goes away after entering the data. I find the always visible text to be more user-friendly and opens the door for the option to update the message and ensure users will see that update.

**Comment by sudaraka94** [comment]
We can add this right before the location chooser. @angusmcleod what do you think ?

**Comment by angusmcleod** [comment]
@yanokwa @sudaraka94 I've added a warning: https://github.com/angusmcleod/discourse-locations/commit/49f5a136ce8ca109d99429f71af1bd85eeff50b7

<img width="428" alt="screen shot 2018-09-25 at 7 03 58 pm" src="https://user-images.githubusercontent.com/5931623/46004268-cafe8b00-c0f5-11e8-90dc-fe67b4bc8be8.png">

You can edit the text in Customize > Text > user.map_location.warning
