### ISSUE TITLE
Map link not appearing on some posts

### ISSUE THREAD

**Issue by chriscroome** [angusmcleod/discourse-locations#39]
On [this post](https://community.coops.tech/t/worker-coop-weekend-2020/1409) there is no [map link](https://www.openstreetmap.org/way/304507988#map=19/53.23597/-1.70776), whereas on [this post](https://community.coops.tech/t/cotech-at-london-tech-week-2019-june-10th-14th/1239) and [this one](https://community.coops.tech/t/coophack-planning-for-cooperative-fortnight-2019-july-5th-6th/1400) there are map links, any suggestions regarding debugging this?

This has also been [cross posted to `discourse.angusmcleod.com.au`](https://discourse.angusmcleod.com.au/t/map-link-not-appearing-on-some-posts/990).

**Comment by angusmcleod** [comment]
Thanks, I'm going to close this issue and use the record on my sandbox to track it :+1:

**Comment by chriscroome** [comment]
No problem, strangely it appears to have resolved itself.

**Comment by angusmcleod** [comment]
Great! I'll close the report on my sandbox then.

**Comment by chriscroome** [comment]
And even more strange, this bug has re-appeared, I was going to post to the [forum topic](https://thepavilion.io/t/map-link-not-appearing-on-some-posts/990) but the thread is closed so I can't.

Steps to reproduce this, first click to [edit the top post in this thread](https://community.coops.tech/t/worker-coop-weekend-2020/1409) and then click Add Location:

https://wiki.coops.tech/w/images/5/57/Screen1.png

Then type *"Thornbridge Outdoors"* in the *"Number and Street"* field and select *"United Kingdom"* as the country and click *"Find Address"* and then click *"Done"*:

https://wiki.coops.tech/w/images/thumb/4/41/Screen2.png/597px-Screen2.png

And this results in the Location form vanishing:

https://wiki.coops.tech/w/images/7/7e/Screen3.png

And after saving the post there is a location icon but no location:

https://wiki.coops.tech/w/images/a/a7/Screen4.png

Is there anything I could do to help debug this issue?

**Comment by chriscroome** [comment]
Sorry for the unnecessary noise, I rebuilt the Discourse app and the update fixed it.
